txt = "";
xscale = 1;
yscale = 1;
xmid = x + (sprite_get_width(sprite_index) * 0.5);
ymid = y + (sprite_get_height(sprite_index) * 0.5);;
c1 = c_silver;
playTouch = true;
highlight = false;
activeOverlay = "";